---
title: "BEE 4750 Homework 1: Introduction to Using Julia"
pdf-title: "BEE 4750/5750"
pdf-subtitle: "Homework 1: Introduction to Using Julia"
pdf-header-left: "BEE 4750/5750"
pdf-header-right: "Fall 2026"
pdf-footer-left: "Homework 1: Introduction to Using Julia"
pdf-logo-path: "../../_assets/logos/envsys_logo.png"
date: last-modified
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
    typst:
        warning: true
        error: true
        toc: false
        date: "08/24/2026"
execute: 
    echo: true
    eval: true
engine: julia
julia:
  exeflags: ["+1.11.5"]
format-links:
  - format: typst
    text: PDF
    icon: file-earmark-pdf
  - format: ipynb
    text: Notebook
    icon: laptop
---

::: {.content-visible when-format="ipynb"}
**Name**: Vivek Srikrishnan

**ID**:
:::

::: {.callout-important icon=false}
### Due Date

Thursday, 9/03/26, 9:00pm
:::

::: {.content-visible when-format="html"}

:::{.callout-caution}

If you are enrolled in the course, make sure that you fork the [assignment repository]({{< var github_org.repo >}}/hw01) (linked in Ed Discussion) to your own GitHub account, or you may not be able to get help if you run into problems.

:::

:::

## Overview

### Load Environment

The following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.

```{julia}
#| output: false
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

Standard Julia practice is to load all needed packages at the top of a file. If you need to load any additional packages in any assignments beyond those which are loaded by default, feel free to add a `using` statement, though [you may need to install the package](https://viveks.me/environmental-systems-analysis/tutorials/julia-basics.html#package-management).

```{julia}
#| output: false

using Random # allows for random seed generation
using Plots # basic plotting: can also install and use other packages
using Graphs # for making graphs and networks
using GraphRecipes # basic graph generation
using LaTeXStrings # allows for LaTeX formatting in plots
using Distributions # sampling and fitting of probability distributions
using CSV # file I/O for CSV files
using DataFrames # data structure for tabular data
```

```{julia}
#| output: false

# this sets a random seed, which ensures reproducibility of random number generation. You should always set a seed when working with random numbers.
Random.seed!(1)
```

## Problems (Total: 50 Points)


### Problem 1 (10)

***Systems Modeling***:

Three factories are discharging a chemical called Chlororadiated Ureadicarboxyl (or CRUD) into the Riley River. The river inflow (where the first factory's effluent meets the river) has a volume of 500,000 m$^3$/d and a CRUD concentration of 0.2 mg/L. The river velocity is 25 km/d.

* Factory 1  discharges $100,000 \text{m}^3$/\text{d} of effluent with a CRUD concentration of 10 mg/L;
* Factory 2 (10 km downstream from Factory 1) discharges $60,000 \text{m}^3$/\text{d} of effluent with a CRUD concentration of 20 mg/L;
* Factory 3 (15 km downstream from Factory 2) discharges $200,000 \text{m}^3$/\text{d} of effluent with a CRUD concentration of 8 mg/L.

CRUD decays in the river with a first order reaction rate $k=0.45 \text{d}^{-1}$. 

Environmental authorities have taken samples downriver of the three factories and found that the CRUD concentration exceeds the regulatory limit of 1 mg/L.  CRUD can be removed at the source discharge at a cost of $50E^2$ per $1000 \text{m}^3$ treated, where $E$ is the efficiency of removal (the fraction of CRUD removed).

#### Problem 1.1 (2)

Draw a diagram of the river and factory system. Include definitions for any notation you will use.

#### Problem 1.2 (5)

Write down a set of conditions on the removal efficiencies $E_1$, $E_2$, and $E_3$ (where the subscript corresponds to the factory where the effluent is being treated) to guarantee compliance.

#### Problem 1.3 (3)

Without finding an "optimal" solution, reason about which factories ought to treat their effluent at a higher level than the others. This can draw on considerations such as cost, the sequencing of discharges, and the amount of CRUD discharged by each factory, or others.

### Problem 2 (6)

***Systems Perturbations***:

Consider the perturbed phosphorous cycle example from Lecture 2. Now suppose that the initial perturbation at $t=0$ is a 10% reduction in the rate constant for the conversion of phosphorous from organic to inorganic form (through an inhibition of phosphatase activity due to e.g. acidic rain fall). When the new steady state is reached, how much phosphorous will be in each compartment?


### Problem 3 (9)

***Debugging Code***: 

The following subproblems all involve code snippets that require debugging. You are encouraged to use online resources (*e.g.* Julia documentation and forums, Stack Overflow, Reddit, etc) to help find diagnose error messages and find solutions, but make sure that you clearly document which resources you used and how you used them.

#### Problem 3.1 (3)

You've been tasked with writing code to identify the minimum value in an array. You cannot use a predefined function. Your colleague suggested the function below, but it does not return the minimum value.

```{julia}
function minimum(array)
    # initialize the minimum value counter
    min_value = 0
    # update minimum values
    for i in 1:length(array)
        if array[i] < min_value
            min_value = array[i]
        end
    end
    # return found minimum
    return min_value
end

array_values = [89, 90, 95, 100, 100, 78, 99, 98, 100, 95]
@show minimum(array_values);
```

What is the logical flaw in the code? Fix it (describe what you changed rather than reproducing the entire code snippet) and show that your fixed code solves the problem.

#### Problem 3.2 (3)

Your team wants to know the expected payout of an old Italian dice game called *passadieci* (which was analyzed by Galileo as one of the first examples of a rigorous study of probability). The goal of passadieci is to get at least an 11 from rolling three fair, six-sided dice. Your strategy is to compute the average wins from 1,000 trials, but the code you've written below produces a `MethodError`.


```{julia}
# function to simulate a passadieci roll: 3 6-sided dice
function passadieci()
    # this rand() call samples 3 values from the vector [1, 6]
    roll = rand(1:6, 3) 
    return roll
end
# set number of trials and initialize outcome vector
n_trials = 1_000
outcomes = zero(n_trials)
# simulate number of passadieci rolls and count wins
for i = 1:n_trials
    outcomes[i] = (sum(passadieci()) > 11)
end
win_prob = sum(outcomes) / n_trials # compute average number of wins
@show win_prob;
```

What does this `MethodError` mean? Why does this code produce one? Fix the error (describe what you changed rather than reproducing the entire code snippet) and solve the problem.

#### Problem 3.3 (3)

You're interested in writing some code to remove the mean of a vector from all of its components. You've written the following code and tried to test it on a random vector, but your code returns a `MethodError`.

```{julia}
# function to remove mean from a vector
function remove_mean(vect)
    # fucntion to compute the mean
    function compute_mean(vect)
        element_sum = 0 # initialize sum
        # compute mean and return
        for v in vect
            element_sum += v
        end
        return element_sum / length(vect)
    end

    m = compute_mean(vect) # compute mean
    # return demeaned vector
    return vect - m
end

random_vect = rand(1_000)
@show remove_mean(random_vect)
```

What does this `MethodError` mean? Why does this code produce one? Fix the error (describe what you changed rather than reproducing the entire code snippet) and solve the problem.

### Problem 4 (5)

***Loading and Manipulating Data***

The file `fha.csv` contains data^[From the [2023 Federal Highway Administration's Highway Statistics report](https://www.fhwa.dot.gov/policyinformation/statistics/2023/pdf/hm72.pdf)] on the size of American metro areas and the number of miles people drive in each metro area each day. This problem asks you to load and work with this data to get practice with data manipulation in Julia.

#### Problem 4.1 (2) 

Load `fha.csv` into a Julia `DataFrame`. How many rows and columns does the data have?


#### Problem 4.2 (3)

Calculate the number of miles driven per person per day for every metro area. Make a scatterplot of this on the $y$-axis and the population of the city on the $x$-axis. Make sure to label your axes and include a caption clearly describing the plot. Highlight where the New York City and Houston metro areas are on the plot and make a legend clearly labelling any plot features.


### Problem 5 (20)

***Computational Modeling***:

Cheap Plastic Products, Inc. is operating a plant that produces $100 \text{m}^3\text{/day}$ of wastewater that is discharged into Pristine Brook. The wastewater contains $1 \text{kg/m}^3$ of YUK, a toxic substance. The US Environmental Protection Agency has imposed an effluent standard on the plant prohibiting discharge of more than $20 \text{kg/day}$ of YUK into Pristine Brook.

Cheap Plastic Products has analyzed two methods for reducing its discharges of YUK. Method 1 is land disposal, which costs $X_1^2/20$ dollars per day, where $X_1$ is the amount of wastewater disposed of on the land ($\text{m}^3\text{/day}$). With this method, 20% of the YUK applied to the land will eventually drain into the stream (*i.e.*, 80% of the YUK is removed by the soil). 

Method 2 is a chemical treatment procedure which costs \$1.50 per $\text{m}^3$ of wastewater treated. The chemical treatment has an efficiency of $e= 1 - 0.005X_2$, where $X_2$ is the quantity of wastewater ($\text{m}^3\text{/day}$) treated. For example, if $X_2 = 50 \text{m}^3\text{/day}$, then $e = 1 - 0.005(50) = 0.75$, so that 75% of the YUK is removed.

Cheap Plastic Products is wondering how to allocate their wastewater between these three disposal and treatment methods (land disposal, chemical treatment, and direct disposal) to meet the effluent standard while keeping costs manageable. The flow of wastewater through this treatment system is shown in @fig-wastewater. 

```{julia}
#| label: fig-wastewater
#| fig-cap: "System diagram of the wastewater treatment options in Problem 4."
#| echo: true

A = [0 1 1 1;
	0 0 0 1;
	0 0 0 1;
	0 0 0 0]

names = ["Plant", "Land Treatment", "Chem Treatment", "Pristine Brook"]
# modify this dictionary to add labels
edge_labels = Dict((1, 2) => "", (1,3) => "", (1, 4) => "",(2, 4) => "",(3, 4) => "")
shapes=[:hexagon, :rect, :rect, :hexagon]
xpos = [0, -1.5, -0.25, 1]
ypos = [1, 0, 0, -1]

p = graphplot(A, names=names,edgelabel=edge_labels, markersize=0.15, markershapes=shapes, markercolor=:white, x=xpos, y=ypos)
display(p)
```



#### Problem 5.1 (2)

Make a figure showing notation for how YUK moves through the system for a given treatment allocation. Make sure to define your variables. You can make this by modifying the graph above or with an independent figure included in your solution.

::: {.callout.tip}

You can modify the edge labels (by editing the `edge_labels` dictionary in the code) in @fig-wastewater to show how the wastewater allocations result in the final YUK discharge into Pristine Brook. For the `edge_label` dictionary, the tuple $(i, j)$ corresponds to the arrow going from node $i$ to node $j$. The syntax for any entry is `(i, j) => "label text"`, and the label text can include mathematical notation if the string is prefaced with an `L`, as in `L"x_1"` will produce $x_1$.
:::


#### Problem 5.2 (4)

Formulate a mathematical model for the treatment cost and the amount of YUK that will be discharged into Pristine Brook based on the wastewater allocations. This is best done with some equations and supporting text explaining the derivation. Make sure you include, as additional equations in the model, any needed constraints on relevant values. 

::: {.callout .tip}
You can find some basics on writing mathematical equations using the LaTeX typesetting syntax [here](https://viveks.me/environmental-systems-analysis/tutorials/latex-notebook.qmd), and a cheatsheet with LaTeX commands can be found on the course website's [Resources page](https://viveks.me/environmental-systems-analysis/resources/markdown.qmd).
:::

#### Problem 5.3 (3) 

Implement your systems model as a Julia function which computes the resulting YUK discharge and cost for a particular treatment plan. You can return multiple values from a function with a [tuple](https://docs.julialang.org/en/v1/manual/functions/#Tuples-1), as in:
```{julia}
function multiple_return_values(x, y)
    return (x+y, x*y)
end

a, b = multiple_return_values(2, 5)
@show a;
@show b;
```

  To evalute the function over vectors of inputs, you can *broadcast* the function by adding a decimal `.` before the function arguments and accessing the resulting values by writing a *comprehension* to loop over the individual outputs in the vector:
  ```{julia}
  x = [1, 2, 3, 4, 5]
  y = [6, 7, 8, 9, 10]

  output = multiple_return_values.(x, y)
  a = [out[1] for out in output]
  b = [out[2] for out in output]
  @show a;
  @show b;
  ```
  Make sure you comment your code appropriately to make it clear what is going on and why.


Use your function to experiment with 1,000 different combinations of wastewater discharge and treatment. You can do this with either a grid search or by sampling from a [Dirichlet distribution](https://en.wikipedia.org/wiki/Dirichlet_distribution) (a $\text{Dirichlet}(1, n)$ distribution will generate uniformly-weighted $n$-dimensional vectors whose components add up to 1; see the [`Distributions.jl` documentation](https://juliastats.org/Distributions.jl/stable/starting/) for how to sample from probability distributions in Julia). 

Plot the results of these experiments by making a scatterplot of YUK discharge into the lake vs. treatment cost. Make sure to label your axes and include a legend, as well as a caption clearly describing the plot.

#### Problem 5.4 (3)

Do any satisfy the YUK effluent standard (plot this as well as a dashed red line). What was the cost of solutions satisfying the standard? 

#### Problem 5.5 (4)

What can you say about the tradeoff between treatment cost and YUK discharge? You don't have to find an "optimal" solution to this problem, but what do you think would be needed to find a better solution? 

#### Problem 5.6 (4)

Find the strategies which minimize cost and YUK discharge (these will be different strategies) analytically and find the values of the objective metrics. Plot these values in the plot that you created for Problem 4.3. How do their values compare to the spread of values that you found in that problem? 


## References

List any external references consulted, including classmates.
